batch_size: 50
epochs: 30
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BIOSCAN-CLIP-hyperbolic_experiments
using_train_seen_for_pre_train: true
dataset: bioscan_1m

image:
  input_type: image
  model: lora_vit
dna:
  input_type: sequence
  model: lora_barcode_bert
language:
  input_type: sequence
  model: lora_bert

hyperbolic_space:
  train_hyperbolic: true
  learn_curv: true
  curv_init: 1.0
  entail_weight: 0.2

  loss_type: 'A'

model_output_name: image_dna_text_hyperbolic_test
model_output_dir: ${project_root_path}/ckpt/bioscan_hyperbolic
evaluation_period: 1
ckpt_path: ${project_root_path}/ckpt/bioscan_hyperbolic/image_dna_text_hyperbolic_2gpu_ep30/2025-03-20_140628/best.pth
output_dim: 768
port: 29535

disable_lora: true
lr_scheduler: one_cycle
lr_config:
  lr: 1e-6
  max_lr: 5e-5

all_gather: true
loss_setup:
  gather_with_grad: true
  use_horovod: false
  local_loss: false
fix_temperature: false
amp: true

random_seed: false

# eval_skip_epoch: 0

default_seed: 42